### ISSUE TITLE
Can you share the instance type of all the candidates and their price?

### ISSUE THREAD

**Issue by xiaofan-luan** [myscale/vector-db-benchmark#1]
Hi Team,
I love your performance benchmark, it's very helpful for users to choose vector databases.

can you give more details about instance types of all candidates and their price?

**Comment by lqhl** [comment]
hi @xiaofan-luan , you can find the instance types in our blog post <https://blog.myscale.com/2023/05/17/myscale-outperform-special-vectordb/>
