### ISSUE TITLE
What is the price for

### ISSUE THREAD

**Issue by liliuleo** [myscale/vector-db-benchmark#2]
Nice work!

It is interesting to do a benchmark based on cost efficiency. However, It looks like `myscale` only supports a free trial, and I didn't see any price-related words on its website (Please CMIIW). Any chance I can know how we evaluate the cost for `myscale`?

**Comment by lqhl** [comment]
Hi @liliuleo, we used our standard pod, which costs $120 per month, for the benchmark. However, during this beta stage, we only offer a free tier. You can find all the specifications of the tested vector databases in [our benchmark blog](https://blog.myscale.com/2023/05/17/myscale-outperform-special-vectordb/) post. We will be releasing information about our pricing and standard tier soon.

**Comment by lqhl** [comment]
Our pricing page: https://myscale.com/pricing
