### ISSUE TITLE
How to run the benchmark with pgvecto.rs?

### ISSUE THREAD

**Issue by VoVAllen** [myscale/vector-db-benchmark#5]
Thanks for your benchmark and it's valuable to us. I saw the client implementation, but not the experiment configuration file. Can you give me some samples for pgvector and pgvecto.rs?

**Comment by lqhl** [comment]
@MochiXu

**Comment by MochiXu** [comment]
> Thanks for your benchmark and it's valuable to us. I saw the client implementation, but not the experiment configuration file. Can you give me some samples for pgvector and pgvecto.rs?

Here we have updated docs for [pgvector](https://github.com/myscale/vector-db-benchmark/blob/master/docs/step-by-step-guide-for-benchmark.md#pgvector).

**Comment by VoVAllen** [comment]
Thanks! @MochiXu
